app/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home),
    path('detail/<int:id>', views.detail, name='detail'),
    path('genre/<int:genre_id>/', views.genre, name='genre'),
    path('country/<int:country_id>/', views.country, name='country'),
    path('search/', views.search, name='search'),
    path('rate_movie/<int:movie_id>/',views.rate_movie, name='rate_movie'),
    path('lovemovie/<int:movie_id>/',views.lovemovie, name='lovemovie'),
    path('lovelist/', views.lovelist, name='lovelist'),
    path('video/<int:id>',views.video, name='video'),
    path('comment/<int:movie_id>/', views.create_comment, name= "comment"),
    path('lang/<int:lang_id>/', views.switchLang, name= "switchLang")
]

project1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.i18n import i18n_patterns

from app import views as home_views  # Đặt tên riêng để tránh xung đột

urlpatterns =  [
    path('admin/', admin.site.urls),
    path('about/', home_views.about),  # Sử dụng hàm xử lý từ views trực tiếp
    path('reg/', include('reg.urls')),  # 'reg' là tên ứng dụng 
    path("", include('app.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
#app/model.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
#from django.utils.translation import gettext_lazy as _

class Genre(models.Model):# thể loại
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Country(models.Model):#  quốc gia
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class Movie(models.Model): # phim
    title = models.CharField(max_length=255)
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True) #xoa theloai thi theloai phim se ve NULL
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    director = models.CharField(max_length=255, default='Unknown')
    actors = models.CharField(max_length=255, default='Unknown')
    rating = models.FloatField(default=0.0)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='images/', default='path/to/default_picture.jpg')
    trailer_link = models.URLField(default='https://www.youtube.com/?app=desktop')
    video_file = models.CharField(max_length=1024, default='Unknown')
    views = models.PositiveIntegerField(default=0)  # Thêm trường views
    cfav=models.PositiveIntegerField(default=0)  # Thêm trường views
    def __str__(self):
        return self.title
    

class Review(models.Model): # đánh giá
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE) # khi 1 movie bi xoa thi tat ca dgia lquan deu bi xoa
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 11)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.movie} - {self.user}"

class Favorite(models.Model):# danh sách yêu thích của người dùng
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.movie} - {self.user}"# tra ve ten phim va ten user
class Comment(models.Model): # bình luận
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE) # khi 1 movie bi xoa thi tat ca dgia lquan deu bi xoa
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.movie} - {self.user}"# tra ve ten phim va ten user

templates/oldfile/about.html
{% include "nav.html" %}
{% load i18n %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% trans 'about' %}</title>
 

<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'> 
    <style> 
  
    body {
        font-family: 'Roboto';font-size: 16px;
    }
    
    .aboutus-section {
        padding: 90px 0;
    }
    .aboutus-title {
        font-size: 30px;
        letter-spacing: 0;
        line-height: 32px;
        margin: 0 0 39px;
        padding: 0 0 11px;
        position: relative;
        text-transform: uppercase;
        color: #000;
    }
    .aboutus-text {
        color: #606060;
        font-size: 60px;
        line-height: 40px;
        margin: 0 0 30px;
    }

 </style>
</head>
  <body>
      <div class="aboutus-section">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="aboutus">

                        <p class="aboutus-text">{% trans "ĐỒ ÁN 1" %}</p>
                        </ul>
                    </div>
                </div>
        <div class="aboutus-banner">
            <img  text-align="center" src="https://dongphucgiadinh.com/wp-content/uploads/2022/09/logo-dai-hoc-bach-khoa.png"/>
        </div>

            </div>
        </div>
    </div>
  </body>
</html>

templates/oldfile/country.html
{% load static %}
{%include "nav.html"%}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cards Gallery</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
    <link rel="stylesheet" href="{% static 'css/cards-gallery.css' %}">
</head>
<body>
   <section class="gallery-block cards-gallery">
	    <div class="container">
	        <div class="heading">
                <h2>{%if not movie%}chưa có film thuộc quốc gia này {%else%} {{country}} {%endif%}</h2>
	        </div>
	        <div class="row">
              {% for item in movie %}
              <div class="col-md-6 col-lg-4">
                <div class="card border-0 transform-on-hover">
                    <a class="lightbox" href="">
                        <div class="card-img-container">
                            <a href="{% url 'detail' id=item.id %}"><!--nhung thang link-->
                            <img src="{{ item.thumbnail.url }}" alt="{{ item.title }}" class="card-img-top">
                            </a>
                        </div>
                    </a>
                    <div class="card-body">
                        <h6><a href="{% url 'detail' id=item.id %}">{{ item.title }}</a></h6>
                        <p class="text-muted card-text">{{ item.actors }}</p>
                    </div>
                </div>
            </div>
            

              {% endfor %}

	        </div>
	    </div>
    </section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.cards-gallery', { animation: 'slideIn'});
    </script>
</body>
</html>

templates/oldfile/detail.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{ mymember.title }} - Movie Detail</title>
      <link rel="stylesheet" href="{% static 'css/detail.css' %}">
   </head>
   <body>
      {% include "nav.html" %}
      <div class="container">
         <div class="card">
            <div class="cover">
               <img src="{{ mymember.thumbnail.url }}" alt="Movie Thumbnail" class="img-cover">
               <a href="{{ mymember.trailer_link }}" class="view-trailer">Trailer</a>
               <div class='movie-info'>
                  {% if request.user.is_authenticated %}
                  <div style='display: flex; gap: 20px; margin-top: 10px;'>
                     <form method="post" action="{% url 'rate_movie' movie_id=mymember.id %}">
                        {% csrf_token %}
                        <label for="id_rating"></label>
                        {{ form.rating }}
                        <button type="submit" class="btn btn-warning">{% trans "Gửi Đánh Giá" %}</button>
                     </form>
                     <form action="{% url 'lovemovie' movie_id=mymember.id %}" method="GET">
                        {% csrf_token %}
                        <div class="small-button">
                           {% if is_favorite %}
                           <button id="ifavoriteButton" class="btn btn-primary">{% trans "Đã yêu Thích" %}</button>
                           {% else %}
                           <button id="ifavoriteButton" class="btn btn-danger">{% trans "Yêu Thích" %}</button>
                           {% endif %}
                        </div>
                     </form>
                  </div>
                  {% else %}
                  <p><em>{%trans "Đăng nhập để đánh giá" %}</em></p>
                  {% endif %}
                  <div>
                     <a href="{% url 'video' id=mymember.id %}">
                     <button type="button" class="btn btn-info">{% trans "Xem Phim" %}</button>
                     </a>
                  </div>
                  <h1 class="title">{{ mymember.title }}</h1>
                  <div class="rating">{{ mymember.rating|floatformat:1 }}/10</div>
               </div>
            </div>
            <div class="detail">
               <h2>{% trans "Thông Tin Phim" %}</h2>
               <div class="info">
                  <p class="director" >
                     <span style="color:black; font-weight:bold">{% trans "Đạo Diễn:" %}</span> 
                     {{ mymember.director }}
                  </p>
                  <p class="actors">
                     <span style="color:black; font-weight:bold">{% trans "Diễn Viên:" %}</span> 
                     {{ mymember.actors }}
                  </p>
                  <p class="genre">
                     <span style="color:black; font-weight:bold">{% trans "Thể Loại:" %}</span> 
                     
                         {% if mymember.genre.name == "Hanh Dong" %}
                             {% trans "Hành Động" %}
                         {% elif mymember.genre.name == "Tinh Cam" %}
                             {% trans "Tình Cảm" %}
                         {% elif mymember..name == "Kinh Di" %}
                             {% trans "Kinh Dị" %}
                         {% elif mymember.genre.name == "Lang Man" %}
                             {% trans "Lãng Mạn" %}
                         {% elif mymember.genre.name == "Phim Hai" %}
                             {% trans "Phim Hài" %}
                         {% elif mymember.genre.name  == "Chien Tranh" %}
                             {% trans "Chiến Tranh" %}
                         {%else %}
                             null
                         {% endif %}
                 </p>
                 
               </div>
               <div class="description">
                  <p>{{ mymember.description }}</p>
               </div>
               <!--cai nay la comment-->
               {% if request.user.is_authenticated %}
               <div class="container mt-5">
                  <div class="d-flex justify-content-center row">
                     <div class="col-md-8">
                        <div class="d-flex flex-column comment-section">
                           <div class="bg-light p-2">
                              <div class="d-flex flex-row align-items-start">
                                 <!-- Hiển thị hình ảnh của người dùng đang đăng nhập -->
                                 <img class="rounded-circle" src="https://i.imgur.com/RpzrMR2.jpg" width="40">
                                 <textarea class="form-control ml-1 shadow-none textarea" id="comment-text" placeholder="Viết binh luận ở đây..."></textarea>
                              </div>
                              <div class="mt-2 text-right">
                                 <!-- Thêm sự kiện onclick để gửi bình luận mới -->
                                 <button class="btn btn-primary btn-sm shadow-none" type="button" onclick="submitComment()">{% trans "Đăng Comment" %}</button>
                                 <button class="btn btn-outline-primary btn-sm ml-1 shadow-none" type="button">{% trans "Thoát" %}</button>
                              </div>
                           </div>
                           {% for comment in comments reversed  %}
                           <div class="bg-white p-2">
                              <div class="d-flex flex-row user-info">
                                 <!-- Hiển thị hình ảnh người dùng và tên người dùng -->
                                 <div class="d-flex flex-column justify-content-start ml-2">
                                    <!-- Làm đậm tên người dùng -->
                                    <span class="d-block font-weight-bold name" style="color: black; font-weight: bold; font-size:22px"> {{ comment.user.username }}</span>
                                 </div>
                              </div>
                              <div class="mt-2">
                                 <!-- Đổi màu chữ và làm đậm nội dung bình luận -->
                                 <p class="comment-text" style="color: black"><em>{{ comment.comment }}</em></p>
                              </div>
                           </div>
                           {% endfor %}
                        </div>
                     </div>
                  </div>
               </div>
               {% else %}
               <p style="color:black; font-weight:bold"><em>{% trans "Đăng Nhập Để Bình Luận" %}</em></p>
               {% endif %}
               <script>
                function submitComment() {
                    var commentText = document.getElementById("comment-text").value;
                    if (commentText.trim() !== "") {
                        var movieId = "{{ mymember.id }}";
                        var url = "{% url 'comment' movie_id=mymember.id %}";
            
                        var formData = new FormData();
                        formData.append('comment', commentText);
            
                        fetch(url, {
                            method: 'POST',
                            body: formData,
                            headers: {
                                'X-CSRFToken': '{{ csrf_token }}'
                            }
                        })
                        .then(response => {
                            if (response.ok) {
                                // Reload lại trang sau khi post comment thành công
                                location.reload();
                            }
                            throw new Error('Network response was not ok.');
                        })
                        .catch(error => {
                            console.error('There was an error!', error);
                        });
                    }
                }
            </script>
            
               <!--het comment-->

            </div>
         </div>
      </div>
   </body>
</html>

templates/oldfile/genre.html
{% load static %}
{%include "nav.html"%}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cards Gallery</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
    <link rel="stylesheet" href="{% static 'css/cards-gallery.css' %}">
</head>
<body>
   <section class="gallery-block cards-gallery">
	    <div class="container">
	        <div class="heading">
             <h2>{%if not movie%}chưa có film thuộc thể loại này {%else%} {{genre}} {%endif%}</h2>
	        </div>
	        <div class="row">
              {% for item in movie %}
              <div class="col-md-6 col-lg-4">
                <div class="card border-0 transform-on-hover">
                    <a class="lightbox" href="">
                        <div class="card-img-container">
                            <a href="{% url 'detail' id=item.id %}">
                            <img src="{{ item.thumbnail.url }}" alt="{{ item.title }}" class="card-img-top">
                            </a>
                        </div>
                    </a>
                    <div class="card-body">
                        <h6><a href="{% url 'detail' id=item.id %}">{{ item.title }}</a></h6>
                        <p class="text-muted card-text">{{ item.actors }}</p>
                    </div>
                </div>
            </div>
            

              {% endfor %}

	        </div>
	    </div>
    </section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.cards-gallery', { animation: 'slideIn'});
    </script>
</body>
</html>

templates/oldfile/index.html
{%load static%}
{%load i18n%}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{{ mymember.title }} - Movie Detail</title>
      <link rel="stylesheet" href="{% static 'css/video.css' %}">
   </head>
   <body>
      {% include "nav.html" %}
      <div class="container">
         <div class="card">
            <div class="cover">
               {{ mymember.video_file | safe }}
               <div class='movie-info'>
                  <h1 class="title">{{ mymember.title }}</h1>
                  <a href="{% url 'detail' id=mymember.id %}">
                  <button type="button" class="btn btn-info">Back to detail</button>
                  </a>
               </div>
            </div>
            <div class="detail">
                <div class="info">
                  <p class="director" >
                     <span style="color:black; font-weight:bold">{% trans "Đạo Diễn:" %}</span> 
                     {{ mymember.director }}
                  </p>
                  <p class="actors">
                     <span style="color:black; font-weight:bold">{% trans "Diễn Viên:" %}</span> 
                     {{ mymember.actors }}
                  </p>
                  <p class="genre">
                     <span style="color:black; font-weight:bold">{% trans "Thể Loại:" %}</span> 
                     
                         {% if mymember.genre.name == "Hanh Dong" %}
                             {% trans "Hành Động" %}
                         {% elif mymember.genre.name == "Tinh Cam" %}
                             {% trans "Tình Cảm" %}
                         {% elif mymember..name == "Kinh Di" %}
                             {% trans "Kinh Dị" %}
                         {% elif mymember.genre.name == "Lang Man" %}
                             {% trans "Lãng Mạn" %}
                         {% elif mymember.genre.name == "Phim Hai" %}
                             {% trans "Phim Hài" %}
                         {% elif mymember.genre.name  == "Chien Tranh" %}
                             {% trans "Chiến Tranh" %}
                         {%else %}
                            null
                         {% endif %}
                 </p>
                 
                 </div>
               <div class="description">
                  <p>{{ mymember.description }}</p>
               </div>
            </div>
         </div>
      </div>
   </body>
</html>

templates/oldfile/list.html
{% load static %}
{%include "nav.html"%}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
    <link rel="stylesheet" href="{% static 'css/cards-gallery.css' %}">
</head>
<body>
   <section class="gallery-block cards-gallery">
	    <div class="container">
	        <div class="heading">
	          <h2>Movie</h2>
	        </div>
	        <div class="row">
             {% for item in mylist %}
              <div class="col-md-6 col-lg-4">
                <div class="card border-0 transform-on-hover">
                    <a class="lightbox" href="">
                        <div class="card-img-container">
                            <a href="detail/{{ item.id }}">
                            <img src="{{ item.thumbnail.url }}" alt="{{ item.title }}" class="card-img-top">
                            </a>
                        </div>
                    </a>
                    <div class="card-body">
                        <h6><a href="detail/{{ item.id }}">{{ item.title }}</a></h6>
                        <p class="text-muted { card-text">{{ item.actors }}</p>
                    </div>
                </div>
            </div>
              {% endfor %}

	        </div>
	    </div>
    </section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.cards-gallery', { animation: 'slideIn'});
    </script>
</body>
</html>

templates/oldfile/lovelist.html
{% load static %}
{%include "nav.html"%}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cards Gallery</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
    <link rel="stylesheet" href="{% static 'css/cards-gallery.css' %}">
</head>
<body>
   <section class="gallery-block cards-gallery">
	    <div class="container">
	        <div class="heading">
	        <!-- <h2>Favourite</h2>--> 
            <h2>{%if not results%}Chưa có film yêu thích {%else%} Favourite{%endif%}</h2>
	        </div>
	        <div class="row">
              {% for item in results %}
              <div class="col-md-6 col-lg-4">
                <div class="card border-0 transform-on-hover">
                    <a class="lightbox" href="">
                        <div class="card-img-container">
                            <a href="{% url 'detail' id=item.movie.id %}">
                            <img src="{{ item.movie.thumbnail.url }}" alt="{{ item.movie.title }}" class="card-img-top">
                            </a>
                        </div>
                    </a>
                    <div class="card-body">
                        <h6><a href="{% url 'detail' id=item.id %}">{{ item.movie.title }}</a></h6>
                        <p class="text-muted card-text">{{ item.movie.actors }}</p>
                    </div>
                </div>
            </div>
              {% endfor %}

	        </div>
	    </div>
    </section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.cards-gallery', { animation: 'slideIn'});
    </script>
</body>
</html>

templates/oldfile/nav.html
{% load i18n %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Movie Critics</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
 <style> 
    #dndk {
        display: block; 
        background-color: #ddd; 
        text-align: center; 
        padding: 10px;
        border-radius: 8px; 
        text-decoration: none; 
        color: #333; 
        margin-left: 15px;
        margin-right: 15px;
        padding: 10px 20px 10px 20px;
    }
  
 </style>

</head>
  <body >
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style = ' 
       position: fixed;top:0;
     z-index: 10; width:100%;'>
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Project 1</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">{% trans "Trang chủ" %}</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans "Thể Loại"%}
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/genre/1">{% trans "Hành Động"%}</a></li>
                <li><a class="dropdown-item" href="/genre/2">{% trans "Tình Cảm"%}</a></li>
                <li><a class="dropdown-item" href="/genre/3">{% trans "Kinh Dị"%}</a></li>
                <li><a class="dropdown-item" href="/genre/4">{% trans "Phim Hài"%}</a></li>
                <li><a class="dropdown-item" href="/genre/5">{% trans "Chiến tranh"%} </a></li>
                <li><a class="dropdown-item" href="/genre/6">{% trans "Lãng mạn"%}</a></li>
              </ul>
            </li>
  
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans "Quốc Gia"%}
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/country/2">{% trans "Mỹ"%}</a></li>
                <li><a class="dropdown-item" href="/country/3">{% trans "Hàn"%}</a></li>
                <li><a class="dropdown-item" href="/country/1">{% trans "Nhật"%}</a></li>
                <li><a class="dropdown-item" href="/country/4">{% trans "Việt"%} </a></li>
                <li><a class="dropdown-item" href="/country/5">{% trans "Trung"%} </a></li>
  
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/about">{% trans "Giới thiệu" %}</a>
            </li>
  

              {% if request.user.is_authenticated %}
                  <!---->
                  
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/lovelist">{% trans "Yêu thích"%}</a>
            </li>
  

                        <li class="nav-item-d">
                          <a id="dndk" aria-current="page" href="#">hello {{user.username}}</a>
                    </li>
                    <li class="nav-item-d">
                      <a id="dndk" aria-current="page" href="{% url 'logout'%}">{% trans "Đăng Xuất "%}</a>
                    </li>

               {% else %}
                        <li class="nav-item-d">
                          <a id="dndk" aria-current="page" href="{% url 'signin' %}">{% trans "Đăng Nhập "%}</a>
                    </li>
                    <li class="nav-item-d">
                      <a id="dndk" aria-current="page" href="{% url 'signup' %}">{% trans "Đăng Ký "%}</a>
                    </li>
               {%endif%}
  
               <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {% trans "Ngôn Ngữ"%}
                </a>
                <form>
                  {%csrf_token%}
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'switchLang' lang_id=1 %}">English</a></li>
                  <li><a class="dropdown-item" href="{% url 'switchLang' lang_id=2 %}">VietNam</a></li>
                </ul>
              </form>
              </li>
  
          </ul>

        <form class="d-flex" action="{% url 'search' %}" method="GET">
          <input class="form-control me-2" type="search" style="font-style:italic" placeholder="{% trans 'Nhập nội dung' %}" aria-label="Search" name="q">
          <button class="btn btn-outline-success" type="submit">{%trans "Tìm Kiếm"%}</button>
        </form>
        </div>
      </div>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>